[package]
name = "xcolor"
version = "0.1.0"
description = "Color picker for X11"
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["color", "utility", "color-picker", "x11"]

[dependencies]
xcb = "0.8.2"
failure = "0.1.1"
structopt = "0.2.5"

[profile.release]
lto = true
panic = "abort"

[badges]
travis-ci = { repository = "Soft/xcolor" }
